"""Restore the wiki_pages indexes that migration 018 dropped.

Migration 018 was autogenerated against a pre-015 database. Because alembic/env.py had
no include_object filter, autogenerate reflected four raw-SQL indexes it could not find
in Base.metadata and emitted drop_index for all of them. Nothing in 019-027 restored
them.

What was lost, and why each matters:

  uq_wiki_pages_slug_scope   the ONLY uniqueness guarantee on (slug, scope_type,
                             scope_id). Without it, create_page's check-then-insert can
                             produce duplicate pages, and get_page_by_slug's .first()
                             then picks one arbitrarily — every later edit lands on one
                             duplicate while the other silently rots but still appears
                             in list and search results. It also made the IntegrityError
                             handler in wiki_compiler.apply_create dead code.

  ix_wiki_pages_kt_slugs     the only index able to serve the RBAC filter
                             (knowledge_type_slugs && ARRAY[...]) applied on every
                             list_pages and search_pages_semantic call.

  ix_wiki_pages_fulltext     GIN over to_tsvector(content_md).

The fourth, ix_wiki_pages_source_ids, is deliberately NOT restored here: 015 dropped
the wiki_pages.embedding column that 018's downgrade tried to rebuild, and the column
this index covered is queried with `= ANY(col)`, which no GIN index can serve. That
query needs to move to `@>` first (issue #39); the index is restored alongside it.

Revision ID: 028
Revises: 027
"""

from typing import Sequence, Union

from alembic import op

revision: str = "028"
down_revision: Union[str, None] = "027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The sentinel must match 010_workspace_wiki_scope.py exactly, or the index will not
# enforce uniqueness for the global scope (where scope_id IS NULL).
_NIL_UUID = "00000000-0000-0000-0000-000000000000"


def upgrade() -> None:
    # --- 1. Dedupe before adding the constraint -------------------------------------
    # Any duplicates already created during the window where uniqueness was absent
    # would make CREATE UNIQUE INDEX fail. Keep the most recently updated row in each
    # group; re-point child rows at it rather than losing them to a cascade.
    op.execute(
        f"""
        CREATE TEMPORARY TABLE _wiki_dupes AS
        SELECT id AS dupe_id, keep_id FROM (
            SELECT
                id,
                FIRST_VALUE(id) OVER (
                    PARTITION BY slug, scope_type, COALESCE(scope_id, '{_NIL_UUID}'::uuid)
                    ORDER BY updated_at DESC, id
                ) AS keep_id
            FROM wiki_pages
        ) ranked
        WHERE id <> keep_id
        """
    )

    # Re-point children of the losing rows at the surviving row. Revisions and
    # contributions carry provenance we do not want to destroy silently.
    op.execute(
        """
        UPDATE wiki_page_revisions r SET page_id = d.keep_id
        FROM _wiki_dupes d WHERE r.page_id = d.dupe_id
        """
    )
    op.execute(
        """
        UPDATE wiki_page_drafts dr SET page_id = d.keep_id
        FROM _wiki_dupes d WHERE dr.page_id = d.dupe_id
        """
    )
    # wiki_page_contributions is keyed on (page_id, source_id); re-pointing can collide
    # with an existing row for the survivor, so drop the losers' rows that would
    # duplicate and re-point the rest.
    op.execute(
        """
        DELETE FROM wiki_page_contributions c
        USING _wiki_dupes d
        WHERE c.page_id = d.dupe_id
          AND EXISTS (
            SELECT 1 FROM wiki_page_contributions k
            WHERE k.page_id = d.keep_id AND k.source_id = c.source_id
          )
        """
    )
    op.execute(
        """
        UPDATE wiki_page_contributions c SET page_id = d.keep_id
        FROM _wiki_dupes d WHERE c.page_id = d.dupe_id
        """
    )

    # The four wiki_page_embeddings_<dim> tables also FK to wiki_pages.id with
    # ON DELETE CASCADE. Their rows are deliberately allowed to cascade rather than be
    # re-pointed: embeddings are derived data keyed by content hash, so the survivor's
    # own vectors are already correct, and reembed_all_pages_task can regenerate any
    # gap. Re-pointing would risk attaching a vector computed from the loser's body.
    op.execute("DELETE FROM wiki_pages WHERE id IN (SELECT dupe_id FROM _wiki_dupes)")
    op.execute("DROP TABLE _wiki_dupes")

    # --- 2. Restore the uniqueness guarantee ----------------------------------------
    op.execute(
        f"""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_wiki_pages_slug_scope
        ON wiki_pages (slug, scope_type, COALESCE(scope_id, '{_NIL_UUID}'::uuid))
        """
    )

    # --- 3. Restore the GIN indexes -------------------------------------------------
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_wiki_pages_kt_slugs "
        "ON wiki_pages USING GIN (knowledge_type_slugs)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_wiki_pages_fulltext "
        "ON wiki_pages USING GIN (to_tsvector('simple', content_md))"
    )


def downgrade() -> None:
    # Reversible, unlike 018's downgrade. Dropping these returns the schema to the
    # (broken) post-018 state; the deduplication in upgrade() is not reversible, which
    # is noted here rather than silently ignored.
    op.execute("DROP INDEX IF EXISTS ix_wiki_pages_fulltext")
    op.execute("DROP INDEX IF EXISTS ix_wiki_pages_kt_slugs")
    op.execute("DROP INDEX IF EXISTS uq_wiki_pages_slug_scope")
